### ISSUE TITLE
wav files in `sounds/examples/timedomain` do not play

### ISSUE THREAD

**Issue by khiner** [pkmital/time-domain-neural-audio-style-transfer#2]
All wav files in `sounds/examples/timedomain` seem to by 75kb in size and do not play. I'm very curious to hear your results!

**Comment by pkmital** [comment]
Hi @khiner i'm seeing different sizes on my download of the repo! 

<img width="817" alt="Screen Shot 2020-04-12 at 2 08 36 PM" src="https://user-images.githubusercontent.com/429252/79079989-318ece00-7cc7-11ea-826b-9f17032c4a6a.png">

Perhaps try downloading again?

**Comment by pkmital** [comment]
Feel free to reopen if there's still an issue!
