### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by ahihi** [pkmital/time-domain-neural-audio-style-transfer#3]
hello,

i am trying to run `timedomain.py` on a system with 16GB RAM and running out of memory in `compute_features()`. is there any simple way of running the computations in smaller batches? if not, how much RAM is required?

```
2019-09-11 13:38:51.235211: W tensorflow/core/framework/allocator.cc:107] Allocation of 1509949440 exceeds 10% of system memory.
LLVM ERROR: out of memory
Aborted (core dumped)
```

**Comment by pkmital** [comment]
Make sure you're not trying a super long audio file. Try with for example 3 seconds of audio only to being. If you are still running into issues, try reducing the parameters, e.g. the number of filters from 4096 to 512. You can also increase the hop_length to reduce the memory footprint. 16 GB should be a lot though! Feel free to reopen if any issues.
